version: '3.8'
services:
    app:
        build: .
        container_name: springboot-app
        ports:
            - "8080:8080"
        depends_on:
            - kafka
            - postgres
            - redis
        networks:
            - app-network
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/finaldb
            SPRING_DATASOURCE_USERNAME: admin
            SPRING_DATASOURCE_PASSWORD: admin
            SPRING_REDIS_HOST: redis
            SPRING_REDIS_PORT: 6379
            SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
            SPRING_PROFILES_ACTIVE: docker
