spring:
    datasource:
        url: jdbc:postgresql://postgresql:5432/finaldb
        username: admin
        password: admin
    
    data:
        redis:
            host: redis
            port: 6379
    
    kafka:
        bootstrap-servers: kafka:9092
