server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://postgres:5432/finaldb
        driver-class-name: org.postgresql.Driver
        username: admin
        password: admin
    
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    
    data:
        redis:
            host: redis
            port: 6379
    
    kafka:
        # change to localhost:9092 to run on intellij, kafka:9092 to run on docker
        bootstrap-servers: localhost:9092

kafka:
    topic:
        name: message-topic
        dlt-name: message-topic.DLT
