server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://postgres:5432/finaldb
        driver-class-name: org.postgresql.Driver
        username: admin
        password: admin
    
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                
    data:
        redis:
            host: redis
            port: 6379
    
    kafka:
        bootstrap-servers: kafka:9092
        consumer:
            group-id: message_group
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
        listener:
            ack-mode: record
            missing-topics-fatal: false
            concurrency: 1
            type: single
        
kafka:
    topic:
        name: message-topic
        dlt-name: message-topic.DLT
